name: "LevelTools"
version: "${version}"
main: "me.byteful.plugin.leveltools.LevelToolsPlugin"
author: byteful
description: "A plugin that adds a leveling system to tools, swords, and bows."
website: "https://byteful.me"
api-version: "1.14"
softdepend:
  - PlaceholderAPI
permissions:
  leveltools.admin:
    description: "Permission to use admin commands."
    default: op
  leveltools.enabled:
    description: "Permission to let a player level up a tool."
    default: true